spring.application.name=hospital-management

# Server Port
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Hospital_db
spring.datasource.username=postgres
spring.datasource.password=vishal
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=ThisIsSuperSecretKeyForHospitalManagementSystemJwt123
jwt.expiration=3600000